# Generated by Django 4.1 on 2022-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=2)),
                ('name', models.CharField(max_length=25)),
                ('native', models.CharField(max_length=25)),
            ],
            options={
                'unique_together': {('code', 'name', 'native')},
            },
        ),
    ]
