version: '3.9'

services:
  postgres:
    container_name: postgres_container
    image: postgis/postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SuperSecret}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - web-app
    restart: always
  
  redis:
    container_name: redis_container
    image: redis
    volumes: 
      - ./volumes/redis:/data
    ports: 
      - '6379:6379'
    networks:
      - web-app
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - web-app

networks:
  web-app: {}