# Generated by Django 4.1 on 2022-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geoname_id', models.PositiveIntegerField(null=True)),
                ('capital', models.CharField(blank=True, max_length=163)),
                ('is_eu', models.BooleanField(default=False)),
                ('languages', models.ManyToManyField(blank=True, to='languages.language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
